### ISSUE TITLE
Feature Request for calculations

### ISSUE THREAD

**Issue by gamassey** [git-hemant/LC-automatique#1]
Expand the syntax to allow a calculated value after a "greaterThan" or "lessThan" in the filter section of the config file. 

example: 
                "installment": {
                          "_comment": "only select loans where the monthly payment is less that 10% of monthly  income",
                    "lessThan": (annualinc/12)/.10)
                },

**Comment by git-hemant** [comment]
Added this feature and now on RHS side of lessThan or greaterThan can be either numeric literal or complex expression

Following are the two examples of it's usage

Example 1: Check monthly income is 10 times of the installment.

```
           "annualInc": {
                "greaterThan": "((loanAmount/term) * 12) * 10"
            }
```

Example 2: Check installment is less than 1/10 of monthly income.

```
    "installment": {
        "lessThan": (annualInc/12)/.10)
    }
```
